### ISSUE TITLE
Custom callback names

### ISSUE THREAD

**Issue by RichAbrahams** [lamp/superagent-jsonp#17]
Was the custom callback name feature merged?

If so how do you use it?

Thanks.

**Comment by lamp** [comment]
Hi, the feature was merged and you use it like so:

```
superagent.get('http://example.com/foo.json').use(jsonp({
  callbackParam:'jsoncallback'
})).end(function(err, res){
  // everything is as normal
});
```

I will check I released this version to npm for you.

**Comment by lamp** [comment]
No, I did not release that to npm, I will do so tonight.

**Comment by RichAbrahams** [comment]
Ok, thanks very much.

**Comment by lamp** [comment]
Just FYI, I only managed to publish the 0.0.7 version today.
