### ISSUE TITLE
404 error support

### ISSUE THREAD

**Issue by lilrogalski** [lamp/superagent-jsonp#19]
What is the preferred way to handle a 404 error on a jsonp request?

I'm using superagent & superagent-jsonp to query the Tumblr API, but currently there is no way that I can see to handle the case that the blog I am searching for doesn't exist. I know that jsonp doesn't support error handling, but some other libraries have ways around this.

My request (using coffeescript): 

request url: `http://api.tumblr.com/v2/blog/testi.tumblr.com/posts/photo?api_key=MYKEY&offset=0&callback=superagentCallback1466647941883982`

```
superagent
  .get url 
  .use jsonp
  .query data 
  .end (err, res) ->
    if err 
      # is there any way to handle a 404 error here?
```

Thanks for building such a helpful tool.

**Comment by lamp** [comment]
The only way I can think of handling it is by adding a timeout.

I'll investigate the possibility of adding this functionality and a configurable timeout setting and see what I can do.

**Comment by lamp** [comment]
Hi @ryanrogalski, I have added support to handle timouts in this pull request here: https://github.com/lamp/superagent-jsonp/pull/20

If you have time, could you please run it through a quick QA for me.

You can add it to your package.json file with: 

```
{
  "dependencies" : {
    "superagent-jsonp" : "git://github.com/lamp/superagent-jsonp.git#add-timeout-support"
  }
}
```

Take a look and let me know what you think, If so, then it will be released sometime this week as 0.1.0.

**Comment by lilrogalski** [comment]
@lamp wow thanks so much, I will check this out later today

**Comment by lilrogalski** [comment]
@lamp this looks great man, thanks for adding this
