### ISSUE TITLE
Unable to set callbackName as an optional parameter

### ISSUE THREAD

**Issue by andygirvan** [lamp/superagent-jsonp#21]
As per the readme, I attempted to add `callbackName` as an option, however looking at the code, it looks like it doesn't check for any config changes to the option `callbackName`.

Line 54:
`callbackName:  'superagentCallback' + new Date().valueOf() + parseInt(Math.random() * 1000),`

should be 
`callbackName: config.callbackName || 'superagentCallback' + new Date().valueOf() + parseInt(Math.random() * 1000)`

**Comment by andygirvan** [comment]
I've raised a pull request at:
https://github.com/lamp/superagent-jsonp/pull/22

Thanks!

**Comment by lamp** [comment]
Cool, will merge now. 

Thank you for helping!
