### ISSUE TITLE
Default timeout value in config is not set. Config.timeout is undefined.

### ISSUE THREAD

**Issue by ascii-husky** [lamp/superagent-jsonp#23]
This check seems to fail:
`var config = arguments.length <= 0 || arguments[0] === undefined ? { timeout: 1000 } : arguments[0];`
If arguments is an emtpy object or timeout ist not set in the arguments object.
Config.timeout stays undefined and each call triggers an error. Is this the intended behaviour?

**Comment by lamp** [comment]
Hmm, seems to be an issue with webpack's transpilation, check the original code here: https://github.com/lamp/superagent-jsonp/blob/master/src/superagent-jsonp.js#L44

And this does not support partial objects, I will fix this tonight. 

Many thanks

**Comment by lastw** [comment]
Similar problem is there: https://github.com/lamp/superagent-jsonp/blob/b11b950a251337f532de8c3c4203867dcdc087a7/src/superagent-jsonp.js#L18

```
request.end = end.bind(request)(requestOrConfig)
```

If I'm using plugin like `superagent.get('/some/url').use(jsonp)`, `requestOrConfig` is `request`, so both context and first argument are `request`, and `timeout` field is function, not default timeout.

**Comment by marcalexiei** [comment]
HI @ascii-husky,
this issue has been fixed on 0.2.0
