### ISSUE TITLE
TypeError: Cannot read property 'push' of undefined

### ISSUE THREAD

**Issue by gwuhaolin** [lamp/superagent-jsonp#4]
Here is code,

```
SuperAgent.get('http://search.jd.com/bookadvsearch')
        .query({
            isbn: isbn,
        }).end(function (err, res) {})
```

Throw Error: TypeError: Cannot read property 'push' of undefined
at 

```
 }).end(function (err, res) {})
```

**Comment by lamp** [comment]
Hi, sorry I didn't see this until now, did you ever solve it?

Or get a stack trace?

**Comment by maverick-zhn** [comment]
How did you solve it? I have the same problem with superagent 2.0.0. Perhaps is user error, I would appreciate any help.
