### ISSUE TITLE
Make compatible with newer versions of superagent

### ISSUE THREAD

**Issue by ntucker** [lamp/superagent-jsonp#9]
Package version is super old and using this is a newer version breaks everything.

**Comment by lamp** [comment]
Hey, could I get some more information about your issue?

I have tested this with v1.3 of superagent and it seems to work fine.

**Comment by albertchan** [comment]
The package currently doesn't work with superagent v1.4+. Any ideas on whether the package will be updated soon?

**Comment by ntucker** [comment]
@albertchan I just made my own thing since this doesn't work: https://ntucker.true.io/ntucker/jsonp-plugin-for-superagent/
